# SDLC Pipeline Engine Configuration

# AI Configuration
ai_config:
  openai:
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    default_model: "gpt-4"
    organization: "${OPENAI_ORG_ID}"
  
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    base_url: "https://api.anthropic.com"
    default_model: "claude-3-sonnet-20240229"

  google_gemini:
    api_key: "${GOOGLE_API_KEY}"
    base_url: "https://generativelanguage.googleapis.com"
    default_model: "gemini-2.0-flash"

  azure_openai:
    api_key: "${AZURE_OPENAI_KEY}"
    endpoint: "${AZURE_OPENAI_ENDPOINT}"
    api_version: "2024-02-01"
    deployment_name: "${AZURE_DEPLOYMENT_NAME}"



# Artifact Storage Configuration
artifact_config:
  storage_path: "./artifacts"
  max_storage_size: 10737418240  # 10GB
  retention_days: 365
  compression_enabled: true
  backup_strategy: "local"

# Repository Connector Configuration
repository_config:
  git:
    provider: "github"  # github, gitlab, bitbucket
    token: "${GITHUB_TOKEN}"
    default_org: "${GITHUB_ORG}"
  
  confluence:
    base_url: "${CONFLUENCE_URL}"
    username: "${CONFLUENCE_USERNAME}"
    api_token: "${CONFLUENCE_API_TOKEN}"
    default_space: "${CONFLUENCE_SPACE}"
  
  sharepoint:
    tenant_id: "${SHAREPOINT_TENANT_ID}"
    client_id: "${SHAREPOINT_CLIENT_ID}"
    client_secret: "${SHAREPOINT_CLIENT_SECRET}"
    site_id: "${SHAREPOINT_SITE_ID}"
  
  jira:
    base_url: "${JIRA_URL}"
    username: "${JIRA_USERNAME}"
    api_token: "${JIRA_API_TOKEN}"
    default_project: "${JIRA_PROJECT}"

# Workflow Engine Configuration
workflow_config:
  max_concurrent_nodes: 10
  default_timeout_seconds: 1800
  cleanup_interval_hours: 24
  retry_policy:
    max_retries: 3
    retry_delay_seconds: 300

# Validation Engine Configuration
validation_config:
  quality_thresholds:
    minimum_score: 75.0
    error_threshold: 0
    warning_threshold: 5
  
  default_rules:
    - rule: "contains_text"
      severity: "error"
      description: "Must contain required content"
    - rule: "length_check"
      severity: "warning"
      parameters:
        min_length: 100
    - rule: "json_valid"
      severity: "error"
      description: "Must be valid JSON when applicable"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "console"
    - type: "file"
      filename: "pipeline_engine.log"
      max_size: "10MB"
      backup_count: 5

# Security Configuration
security:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  
  authentication:
    jwt_secret: "${JWT_SECRET}"
    token_expiry_hours: 24
  
  audit:
    enabled: true
    log_all_requests: true

# Performance Configuration
performance:
  async_timeout: 300
  max_request_size: "100MB"
  rate_limiting:
    enabled: true
    requests_per_minute: 100
  
  caching:
    enabled: true
    ttl_seconds: 3600
    max_size: "1GB"

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  
  health_check:
    enabled: true
    path: "/health"
    interval_seconds: 30
  
  alerts:
    enabled: true
    webhook_url: "${ALERT_WEBHOOK_URL}"
    thresholds:
      error_rate: 0.05
      response_time_ms: 5000
